### ISSUE TITLE
Could not load the custom kernel for multi-scale deformable attention: /opt/app-root/src/.cache/torch_extensions/py312_cu124/MultiScaleDeformableAttention/MultiScaleDeformableAttention.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by promoteAI** [docling-project/docling-serve#110]
Logs:
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
Could not load the custom kernel for multi-scale deformable attention: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Could not load the custom kernel for multi-scale deformable attention: /opt/app-root/src/.cache/torch_extensions/py312_cu124/MultiScaleDeformableAttention/MultiScaleDeformableAttention.so: cannot open shared object file: No such file or directory
Could not load the custom kernel for multi-scale deformable attention: /opt/app-root/src/.cache/torch_extensions/py312_cu124/MultiScaleDeformableAttention/MultiScaleDeformableAttention.so: cannot open shared object file: No such file or directory
Could not load the custom kernel for multi-scale deformable attention: /opt/app-root/src/.cache/torch_extensions/py312_cu124/MultiScaleDeformableAttention/MultiScaleDeformableAttention.so: cannot open shared object file: No such file or directory
Could not load the custom kernel for multi-scale deformable attention: /opt/app-root/src/.cache/torch_extensions/py312_cu124/MultiScaleDeformableAttention/MultiScaleDeformableAttention.so: cannot open shared object file: No such file or directory
Could not load the custom kernel for multi-scale deformable attention: /opt/app-root/src/.cache/torch_extensions/py312_cu124/MultiScaleDeformableAttention/MultiScaleDeformableAttention.so: cannot open shared object file: No such file or directory
INFO:     172.2.0.4:53933 - "POST /v1alpha/convert/source HTTP/1.1" 500 Internal Server Error
Could not load the custom kernel for multi-scale deformable attention: /opt/app-root/src/.cache/torch_extensions/py312_cu124/MultiScaleDeformableAttention/MultiScaleDeformableAttention.so: cannot open shared object file: No such file or directory

**Comment by Fogapod** [comment]
For context: this happens wtih tesla T4 GPU for me with image I built myself:

```yaml
x-docling-defaults: &docling-defaults
  build:
    dockerfile: Containerfile
    args:
      - UV_SYNC_EXTRA_ARGS=--no-extra=cpu --no-extra=rapidocr
      - MODELS_LIST=layout tableformer picture_classifier easyocr smolvlm
  restart: unless-stopped
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            capabilities: [gpu]
  runtime: nvidia
  shm_size: 100gb
```

These errors are printed once at PDF pipeline initialization. Dont know what are the implications of this, everything seems to work.
Setting `CUDA_HOME` / mounting host cuda directory prints weird compilation errors.

This seems related: https://github.com/huggingface/transformers/issues/35349
They mention CUDA dev files not being included into image being possible cause but I haven't yet figured out how to install cuda properly on ibm image docling uses

**Comment by eightBEC** [comment]
I'm having the same issue with the following prebuilt image: `ghcr.io/docling-project/docling-serve-cu124` 

running on RHOS 4.17 with the deployment as specified in the [Docling documentation](https://github.com/docling-project/docling-serve/blob/main/docs/deploy-examples/docling-serve-oauth.yaml)

How does this relate to: https://github.com/docling-project/docling-serve/issues/54

**Comment by rmdg88** [comment]
hey, sorry for the late reply,
i'm not able to reproduce this issue.
i've deployed the latest, as of today docling-serve version and works with a torch warning, in a OCP cluster with nvidia GPU.
(also tried locally with compose and see no warnings/errors)

- i got a warning regarding torch cache in OCP (not an error)

```
/opt/app-root/lib64/python3.12/site-packages/transformers/models/rt_detr/modeling_rt_detr.py:1734: UserWarning: Specified kernel cache directory could not be created! This disables kernel caching. Specified directory is /opt/app-root/src/.cache/torch/kernels. This warning will appear only once per process. (Triggered internally at /pytorch/aten/src/ATen/native/cuda/jit_utils.cpp:1442.)
level_start_index = torch.cat((spatial_shapes.new_zeros((1,)), spatial_shapes.prod(1).cumsum(0)[:-1]))
```
- making a mount for the dir seems to fix the warning

```
          volumeMounts:
            - name: torch-cache
              mountPath: /opt/app-root/src/.cache/torch/kernels
      volumes:
        - name: torch-cache
          emptyDir: {}
```

- Is this still a issue @promoteAI ? You can try the mount, or provide more details, like cluster version, gpu type.
- In case its resolved, let us also know. Thanks
