### ISSUE TITLE
Error Processing File model.safetensors

### ISSUE THREAD

**Issue by j820301** [docling-project/docling-serve#123]
I encountered the following issue when installing with docker compose, using the ch_tra language in the EasyOCR engine, it says "chinese.pth downloads disabled". 

![Image](https://github.com/user-attachments/assets/105e30d8-2865-4ece-9994-a1b6da05ed7e)

So I downloaded it from the following URL https://github.com/JaidedAI/EasyOCR/releases/download/pre-v1.1.6/chinese.zip and extracted it, obtaining chinese.pth and using volumes: to complete the mount. After restarting and running, I received a new error: Error Processing File model.safetensors. 

![Image](https://github.com/user-attachments/assets/25dbec25-641e-4d09-bcd7-c1653b89c218)

I would like to know if there is a standard solution, how to correctly download the model in docling, for example, docling pull model? Or will docling serve automatically download the required dependencies or models? 
Thank you again to the developers for their hard work, and I am very grateful.

docker-compose.yml 
```
services:
  docling:
    image: ghcr.io/docling-project/docling-serve-cu124:v0.7.0
    container_name: docling
    restart: unless-stopped
    pull_policy: always
    ports:
      - 5001:5001
      - 5002:8080
    environment:
      - DOCLING_SERVE_ENABLE_UI=true
    volumes:
      - ./docling/models:/opt/app-root/src/.cache/docling/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
```

**Comment by dolfim-ibm** [comment]
You could try running with the ENV `DOCLING_SERVE_ARTIFACTS_PATH=""`, then the models will be downloaded at runtime.

What is the content of your models folder?

**Comment by j820301** [comment]
Is the DOCLING_SERVE_ARTIFACTS_PATH configuration also pointing to /docling/docling/models?
Here are the paths and files, and there is also a chinese.pth file inside the chinese_model folder.

  root@ubuntu-template:/docling/docling/models/EasyOcr# ls
  chinese_model  chinese.pth  chinese.zip  craft_mlt_25k.pth

**Comment by j820301** [comment]
I will first modify the configuration as follows, and I will report back here if there are any results. Thank you very much for your answers and contributions.

```
services:
  docling:
    image: ghcr.io/docling-project/docling-serve-cu124:v0.7.0
    container_name: docling
    restart: unless-stopped
    pull_policy: always
    ports:
      - 5001:5001
      - 5002:8080
    environment:
      - DOCLING_SERVE_ENABLE_UI=true
      - DOCLING_SERVE_ARTIFACTS_PATH="/docling/docling/models"
    volumes:
      - ./docling/models:/opt/app-root/src/.cache/docling/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
```
Here are the paths and files, and there is also a chinese.pth file inside the chinese_model folder.

root@ubuntu-template:/docling/docling/models/EasyOcr# ls -l
total 506880
drwxr-xr-x 2 root root      4096 Apr  8 07:59 chinese_model
-rw-r--r-- 1 root root 226062909 Jul  7  2020 chinese.pth
-rw-r--r-- 1 root root 209821039 Dec  7  2021 chinese.zip
-rw-r--r-- 1 root root  83152330 Dec  7  2021 craft_mlt_25k.pth

**Comment by j820301** [comment]
Yesterday, after setting the ENV OCLING_SERVE_ARTIFACTS_PATH, I was happy to have resolved the issue of automatically downloading the model weights. 
Subsequently, several problems were also resolved by configuring the corresponding parameters based on the logs.
The complete configuration file is attached. However, I still have a question: why, after changing the model and setting the ch_tra parameter, does the output JSON still not display Traditional Chinese? How do I configure the language of the output JSON file?

Also, some areas in my image seem to have not been fully recognized and exported by OCR. How can I configure it to effectively obtain the text content in the image?

OCR image
![Image](https://github.com/user-attachments/assets/98dfdf2b-af1c-4f09-adff-0eec39953685)

output JSON file

[file.json](https://github.com/user-attachments/files/19658617/file.json)


Other debugging and parameter configuration.

ENV  CUDA_HOME
![Image](https://github.com/user-attachments/assets/d906c600-4ebe-4c83-bf6e-4a4afce72065)

ENV  CUDA_LAUNCH_BLOCKING=1

![Image](https://github.com/user-attachments/assets/27fd11bc-a9d5-45dd-91cb-ac6bec964d32)

ENV - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

![Image](https://github.com/user-attachments/assets/2e3a667d-e35d-44fa-bc27-40ca71801aaf)

yml file
```
services:
  docling:
    image: ghcr.io/docling-project/docling-serve-cu124:v0.7.0
    container_name: docling
    restart: unless-stopped
    pull_policy: always
    ports:
      - 5001:5001
      - 5002:8080
    environment:
      - DOCLING_SERVE_ENABLE_UI=true
      - DOCLING_SERVE_ARTIFACTS_PATH="/docling/docling/models"
      - CUDA_HOME="/usr/local/cuda-12.5"
      - CUDA_LAUNCH_BLOCKING=1
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    volumes:
      - ./docling/models:/opt/app-root/src/.cache/docling/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
```

If there are any issues with the above configuration, please let me know. I am very happy and grateful for dolfim’s answers and contributions
