### ISSUE TITLE
Docker: Error processing file: CUDA error: no kernel image is available for execution on the device CUDA

### ISSUE THREAD

**Issue by SuperPat45** [docling-project/docling-serve#132]
I need to install docling through docker for use with Open WebUI.
I use image ghcr.io/docling-project/docling-serve-cu124

In my docker compose, I have

```
services:
  docling:
    image: ghcr.io/docling-project/docling-serve-cu124
    container_name: docling
    ports:
      - "5001:5001"
    environment:
      - 'DOCLING_SERVE_ENABLE_UI=true'
    # I also try this:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

```

In the UI when I try to convert a PDF file to Markdown, this error is thrown:

> Error processing file: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. 

Host: Ubuntu 24.10
GPU: Nvidia RTX 5090 with working driver

What I'm done wrong?

**Comment by dolfim-ibm** [comment]
I don't think we have easy access to a system where to try reproducing this. We only used the CUDA image in OpenShift clusters for the moment.

**Comment by rmdg88** [comment]
@SuperPat45

- i was able to make it work, here is my example and configuration steps

compose.yaml

```
services:
  docling:
    image: ghcr.io/docling-project/docling-serve-cu124
    container_name: docling
    ports:
      - 5001:5001
    environment:
      - DOCLING_SERVE_ENABLE_UI=true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 0 # nvidia-smi
            capabilities: [gpu]

```
steps:
```
# check which GPU you want to use (0/1/2/3.. and update compose.yaml file or use 'count: all') available and driver version (for cuda v12.4 we need driver >=550.54.14) https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id6
nvidia-smi

# check if the NVIDIA Container Toolkit is installed/updated
dpkg -l | grep nvidia-container-toolkit

# check which runtime is being used by docker
docker info | grep -i runtime

# (optional) if the NVIDIA Container Toolkit is not installed, install it
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
    | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
    | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
    | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
sudo apt-get update
sudo apt-get install -y nvidia-container-toolkit
sudo nvidia-ctk runtime configure --runtime=docker
sudo systemctl restart docker
docker info | grep -i runtime

# (optional) if the default docker runtime, changes back from 'nvidia' to 'default' after restarting the docker service

# (optional) backup daemon.json file
sudo cp /etc/docker/daemon.json /etc/docker/daemon.json.bak

# (optional) update the daemon.json file
echo '{
  "runtimes": {
    "nvidia": {
      "path": "nvidia-container-runtime"
    }
  },
  "default-runtime": "nvidia"
}' | sudo tee /etc/docker/daemon.json > /dev/null

# (optional) restart the Docker service after updating the daemon.json file
sudo systemctl restart docker

# confirm nvidia is the default runtime used by docker
docker info | grep -i runtime

# run the container
docker compose up -d
```

![Image](https://github.com/user-attachments/assets/f13cc072-6ab1-490b-a7f6-813d688f723e)
