### ISSUE TITLE
Add ROCm Support for PyTorch and Torchvision for AMD GPU Compatibility

### ISSUE THREAD

**Issue by Schwenn2002** [docling-project/docling-serve#178]
PyTorch can also support ROCm with AMD graphics cards. 

It would be helpful if a predefined image for ROCm could be provided as well. Attached is a working configuration using docker-compose and a customized Dockerfile for the installation (`start with docker-compose up -d --build docling-serve`). I have multiple ROCm GPUs and pass only one GPU to the Docker container (`ROCR_VISIBLE_DEVICES=0`).

**docker-compose.yaml**
```
services:
  docling-serve:
    build:
      context: .
      dockerfile: ./docling-serve/Dockerfile
    image: ghcr.io/docling-project/docling-serve-cpu
    container_name: docling-serve
    ports:
      - "5001:5001"
    environment:
      - 'ROCR_VISIBLE_DEVICES=0'
      - 'HSA_OVERRIDE_GFX_VERSION=11.0.0'
      - 'HSA_ENABLE_SDMA=0'
      - 'DOCLING_SERVE_ENABLE_UI=true'
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - 993
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
```

**Dockerfile**
```
FROM ghcr.io/docling-project/docling-serve-cpu

USER 0

# Start
RUN yum update
RUN yum upgrade -y

WORKDIR /

#ROCM Installation
RUN printf "[ROCm-6.3.4]\n\
name=ROCm6.3.4\n\
baseurl=https://repo.radeon.com/rocm/el9/6.3.4/main\n\
enabled=1\n\
priority=50\n\
gpgcheck=1\n\
gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key\n" \
> /etc/yum.repos.d/rocm.repo
RUN dnf clean all -y
RUN dnf install rocm -y

#RUN yum install https://repo.radeon.com/amdgpu-install/6.3.3/rhel/9.6/amdgpu-install-6.3.60303-1.el9.noarch.rpm -y
#RUN amdgpu-install -y --usecase=rocm --no-dkms --release=el9

# Install pytorch ROCM
# Prüfe Torch-Version und installiere ROCm, falls '+cpu' gefunden wird
RUN if pip show torch | grep 'Version' | grep -q '+cpu'; then \
        pip3 uninstall -y torch torchvision torchaudio && \
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.3 --no-cache-dir; \
    else \
                echo "nothing to do..."; \
    fi

# Set the ROCM_HOME environment variable
ENV ROCM_HOME=/opt/rocm

# Add ROCM_HOME to the PATH environment variable
ENV PATH=$ROCM_HOME/bin:$PATH

#Setze LD_LIBRARY_PATH, damit die Bibliotheken zur Laufzeit gefunden werden
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/lib
```
