### ISSUE TITLE
Enh: provide a docker environment

### ISSUE THREAD

**Issue by flefevre** [docling-project/docling-serve#18]
Thanks a lot for the work done at Docling.
I would like if you will provide a Dockerfile and a docker-compose.yml to ease the integration of docling in our startegy.

**Comment by flefevre** [comment]
Any news on this topic.
Do you have any advice to do it?

**Comment by haoshan98** [comment]
> Thanks a lot for the work done at Docling. I would like if you will provide a Dockerfile and a docker-compose.yml to ease the integration of docling in our startegy.

`docker-compose.yml:`
```yaml
services:
  docling:
    image: ghcr.io/ds4sd/docling-serve-cpu:main
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5001/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 20
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - docling

networks:
  docling:
```
