### ISSUE TITLE
Move API to /v1

### ISSUE THREAD

**Issue by dolfim-ibm** [docling-project/docling-serve#238]
Drop support for `/v1alpha` and switch to `/v1`.

This change will **not** be backwards compatible.

## Proposed API specs

```yaml
options: {}  # same as the current version, but without the `return_as_file`
sources:
  - kind: file
     base64_string: ""
     filename: ""
  - kind: http
     url: ""
     headers: {}
  - kind: s3  # [coming soon]
     # ...
target:
  kind: inbody  # default (still have to validate the name)
  kind: zip  # equivalent of using return_as_file in the prev versions
  kind: s3  # [coming soon]
  # ...
  kind: put  # [coming soon] PUT zip to a pre-signed url 
```
